### ISSUE TITLE
Detect and Utilize animations.json from Parent or Child Theme

### ISSUE THREAD

**Issue by ogorzalka** [denisdums/MotionForWP#1]
The MotionForWP plugin currently utilizes its own animations.json file to define animation properties, such as Fade In, Slide Top, Rotate Right, etc. A theme developer can override this by adding a filter. However, allowing themes to provide their own animations.json file could offer greater simplicity of customization and flexibility.

I propose an enhancement that enables the plugin to detect if a parent theme or child theme contains an animations.json file. If detected, the plugin should use that file instead of the default one.

**Proposed Solution:**

1.	Check if the parent theme contains an animations.json file with the structure similar to the default one.
2.	If not found, check if the child theme contains an animations.json file.
3.	If either file is found, utilize it instead of the plugin’s default animations.json.
4.	Provide clear documentation on the structure and requirements of the animations.json file within the theme, ensuring compatibility with the plugin’s animation features.

**Comment by denisdums** [comment]
The support was added since this commit https://github.com/denisdums/MotionForWP/commit/1a5dd55f34ef36d4e443623f9e5eb66e8a05e821
